// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package sounds

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// SoundAssets emits the module script that loads the cuelume glue. It is
// the single place pages reference the sound plugin — replace the bare
// <script src="/static/cuelume.js"> with @sounds.SoundAssets() so the
// plugin owns its own asset loading and can be removed in one spot.
func SoundAssets() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script defer type=\"module\" src=\"/static/cuelume.js\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// SoundToggle renders the navbar mute button. Its state (aria-pressed and
// the visible icon) is driven by web/resources/static/cuelume.js, which
// watches for clicks on [data-sound-toggle] and reflects the effective
// state (user preference AND OS reduced-motion). Mirrors the theme toggle
// styling (app-theme-toggle) for a consistent navbar.
//
// LOCALITY OF BEHAVIOR (why no data-on:click here): the sound plugin must
// work on every page that renders the navbar, including the whiteboard
// board, which deliberately loads NO Datastar (its canvas wiring is plain
// JS — verified in features/whiteboard/components.templ). Datastar's
// data-on:* is inert on that page, so a data-on:click binding would
// silently kill the toggle there (the theme toggle already has this quirk).
// Instead the button declares its contract via data-sound-toggle and the
// plugin's own module wires it with a delegated, idempotent click — the
// same pattern theme.js uses for the theme toggle, and the closest
// declarative approach that works on all pages. Sound-specific declarative
// attributes (data-cuelume-*) on the nav tabs are handled by cuelume's own
// bind(), which is Datastar-independent for the same reason.
func SoundToggle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<button type=\"button\" class=\"app-sound-toggle\" data-sound-toggle aria-label=\"Toggle sound\" aria-pressed=\"true\" title=\"Mute sounds\"><iconify-icon icon=\"material-symbols:volume-up\" class=\"text-lg sound-toggle-icon icon-sound-on\"></iconify-icon> <iconify-icon icon=\"material-symbols:volume-off\" class=\"text-lg sound-toggle-icon icon-sound-off\"></iconify-icon></button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
